name: deploy

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [8]

    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true
    - name: Setup ruby
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.7
    - name: Install Dependencies
      run: |
        sudo apt-get install p7zip-full
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Download Fonts
      run: |
        wget https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.10.2/sarasa-gothic-ttf-0.10.2.7z
        7z x sarasa-gothic-ttf-0.10.2.7z -o./data/fonts/
    - name: Build
      run: |
        bundle exec rake build
    - name: Setup Static Folder
      run: |
        echo "restartruby.com" > ./build/book/book/CNAME
        mkdir ./build/book/book/downloads
        cp ./build/book/book.pdf ./build/book/book/downloads/
        cp ./build/book/book.epub ./build/book/book/downloads/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GH_PAGES }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build/book/book
