name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [8]

    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install_gitbook_plugins
      run: |
        npm install gitbook-cli  -g
        gitbook -v
        gitbook install
    - name: build_gitbook
      run: |
        gitbook build
    - name: cname
      run: |
        echo "restartruby.com" > ./_book/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GH_PAGES }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_book
