name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        ruby: [ 2.7 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.ruby }} CI
    steps:
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run Tests
        run: |
          bundle exec rake test
